name: Swift

on: [push, pull_request]

jobs:
  target_macOS:

    name: Smoke Test (macOS)
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: sudo xcode-select --switch "$(find /Applications -mindepth 1 -maxdepth 1 ! -type l | grep "Xcode_[\.0-9]*app" | sort -V | tail -1)/Contents/Developer"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  target_iOS_simulator:

    name: Smoke Test (iOS Simulator)
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: sudo xcode-select --switch "$(find /Applications -mindepth 1 -maxdepth 1 ! -type l | grep "Xcode_[\.0-9]*app" | sort -V | tail -1)/Contents/Developer"
    - name: Build
      run: xcodebuild build -scheme VideoIO -destination 'platform=iOS Simulator,name=iPhone 11' -workspace .
    - name: Run tests
      run: xcodebuild test -scheme VideoIO -destination 'platform=iOS Simulator,name=iPhone 11' -workspace .

  target_tvOS_simulator:

    name: Smoke Test (tvOS Simulator)
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: sudo xcode-select --switch "$(find /Applications -mindepth 1 -maxdepth 1 ! -type l | grep "Xcode_[\.0-9]*app" | sort -V | tail -1)/Contents/Developer"
    - name: Build
      run: xcodebuild build -scheme VideoIO -destination 'platform=tvOS Simulator,name=Apple TV' -workspace .
    - name: Run tests
      run: xcodebuild test -scheme VideoIO -destination 'platform=tvOS Simulator,name=Apple TV' -workspace .

  target_iOS_device:

    name: Build (iOS Device)
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: sudo xcode-select --switch "$(find /Applications -mindepth 1 -maxdepth 1 ! -type l | grep "Xcode_[\.0-9]*app" | sort -V | tail -1)/Contents/Developer"
    - name: Build
      run: xcodebuild build -scheme VideoIO -destination generic/platform=iOS -workspace .

  target_tvOS_device:

    name: Build (tvOS Device)
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: sudo xcode-select --switch "$(find /Applications -mindepth 1 -maxdepth 1 ! -type l | grep "Xcode_[\.0-9]*app" | sort -V | tail -1)/Contents/Developer"
    - name: Build
      run: xcodebuild build -scheme VideoIO -destination generic/platform=tvOS -workspace .

  target_macCatalyst:

    name: Smoke Test (macCatalyst)
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: sudo xcode-select --switch "$(find /Applications -mindepth 1 -maxdepth 1 ! -type l | grep "Xcode_[\.0-9]*app" | sort -V | tail -1)/Contents/Developer"
    - name: Build
      run: xcodebuild build -scheme VideoIO -destination 'platform=macOS,variant=Mac Catalyst' -workspace .
    - name: Run tests
      run: xcodebuild test -scheme VideoIO -destination 'platform=macOS,variant=Mac Catalyst' -workspace .
